version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Install Python3.6
          command: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install python3.6
            sudo apt-get install python3.6-dev
            sudo apt-get install python3.6-venv
            python3.6 -m venv ~/venv
      - run:
          name: Install dependencies
          command: |
            source ~/venv/bin/activate
            pip install .[tests]
      - run:
          name: Lint
          command: |
            source ~/venv/bin/activate
            flake8
            isort --check-only --diff
            unify --check-only --quote \" -r .
      - run:
          name: Run tests
          command: |
            source ~/venv/bin/activate
            py.test -vv tests/